spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # set @@GLOBAL.sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
    url: jdbc:mysql://192.168.0.211:3306/community_v2
    username: community_v2
    password: communityv2
  servlet:
    multipart:
      max-file-size: 10000MB
      max-request-size: 100000MB
  redis:
    host: 192.168.0.211
#    host: 192.168.136.136
    port: 6379
    database: 0
    timeout: 1800000
    password: xiangjiaochuanmei
#    password:
    jedis:
      pool:
        max-active: 20 #最大连接数
        max-wait: -1    #最大阻塞等待时间(负数表示没限制)
        max-idle: 5    #最大空闲
        min-idle: 0     #最小空闲
server:
  port: 8005

# 选择api项目下的resouces路径下的user文件夹
# filePath: "/Users/yangyida/Documents/project/complaint_system/web-server/src/main/resources/img/user/"
filePath: "D:/Desktop/System/history/Community/Community-system/core/src/main/resources/img/user/"
#D:\Desktop\System\history\Community\Community-system\core\src\main\resources
# 服务器url路径
projecturl: "http://127.0.0.1:8005"


